import solc from 'solc';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
export async function compile() {
  const input = { language: 'Solidity', sources: { 'TinySprout.sol': { content: await readFile(new URL('../contracts/TinySprout.sol', import.meta.url), 'utf8') } }, settings: { optimizer: { enabled: true, runs: 200 }, evmVersion: 'shanghai', outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode.object'] } } } };
  const output = JSON.parse(solc.compile(JSON.stringify(input)));
  const errors = output.errors?.filter(e => e.severity === 'error') ?? [];
  if (errors.length) throw new Error(errors.map(e => e.formattedMessage).join('\n'));
  const contract = output.contracts['TinySprout.sol'].TinySprout;
  const artifact = { abi: contract.abi, bytecode: `0x${contract.evm.bytecode.object}`, deployedBytecode: `0x${contract.evm.deployedBytecode.object}` };
  await mkdir(new URL('../src/chain/', import.meta.url), { recursive: true });
  await writeFile(new URL('../src/chain/contract.ts', import.meta.url), `// Generated by npm run contract:compile.\nexport const abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\nexport const bytecode = '${artifact.bytecode}' as const;\nexport const deployedBytecode = '${artifact.deployedBytecode}' as const;\n`);
  await mkdir(new URL('../artifacts/', import.meta.url), { recursive: true });
  await writeFile(new URL('../artifacts/TinySprout.json', import.meta.url), JSON.stringify(artifact, null, 2));
  await writeFile(new URL('../artifacts/compiler-input.json', import.meta.url), JSON.stringify(input, null, 2));
  return artifact;
}
if (process.argv[1]?.endsWith('/compile.mjs')) { await compile(); console.log('TinySprout compiled (Solidity 0.8.30, Shanghai).'); }
